name: polycloud_ui
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  melos: ^8.8.0

workspace:
  - apps/polycloud
  - packages/polycloud_client_core
  - packages/polycloud_client_oidc
  - packages/polycloud_client_calendar

melos:
  scripts:
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
    format:
      run: melos exec -c 1 -- dart format lib/